launched sample website in created ASG

diff --git a/ec2-autoscaling.yaml b/ec2-autoscaling.yaml
--- a/ec2-autoscaling.yaml
+++ b/ec2-autoscaling.yaml
@@ -12,7 +12,124 @@ Resources:
         KeyName: praneeth
         SecurityGroupIds:
         - !GetAtt praneethSG.GroupId
-        
+        UserData:
+          Fn::Base64: |
+            #!/bin/bash
+
+            # Variable Declaration
+            #PACKAGE="httpd wget unzip"
+            #SVC="httpd"
+            URL='https://www.tooplate.com/zip-templates/2098_health.zip'
+            ART_NAME='2098_health'
+            TEMPDIR="/tmp/webfiles"
+
+            yum --help &> /dev/null
+
+            if [ $? -eq 0 ]
+            then
+              # Set Variables for CentOS
+              PACKAGE="httpd wget unzip"
+              SVC="httpd"
+
+              echo "Running Setup on CentOS"
+              # Installing Dependencies
+              echo "########################################"
+              echo "Installing packages."
+              echo "########################################"
+              sudo yum install $PACKAGE -y > /dev/null
+              echo
+
+              # Start & Enable Service
+              echo "########################################"
+              echo "Start & Enable HTTPD Service"
+              echo "########################################"
+              sudo systemctl start $SVC
+              sudo systemctl enable $SVC
+              echo
+
+              # Creating Temp Directory
+              echo "########################################"
+              echo "Starting Artifact Deployment"
+              echo "########################################"
+              mkdir -p $TEMPDIR
+              cd $TEMPDIR
+              echo
+
+              wget $URL > /dev/null
+              unzip $ART_NAME.zip > /dev/null
+              sudo cp -r $ART_NAME/* /var/www/html/
+              echo
+
+              # Bounce Service
+              echo "########################################"
+              echo "Restarting HTTPD service"
+              echo "########################################"
+              systemctl restart $SVC
+              echo
+
+              # Clean Up
+              echo "########################################"
+              echo "Removing Temporary Files"
+              echo "########################################"
+              rm -rf $TEMPDIR
+              echo
+
+              sudo systemctl status $SVC
+              ls /var/www/html/
+
+            else
+                # Set Variables for Ubuntu
+              PACKAGE="apache2 wget unzip"
+              SVC="apache2"
+
+              echo "Running Setup on CentOS"
+              # Installing Dependencies
+              echo "########################################"
+              echo "Installing packages."
+              echo "########################################"
+              sudo apt update
+              sudo apt install $PACKAGE -y > /dev/null
+              echo
+
+              # Start & Enable Service
+              echo "########################################"
+              echo "Start & Enable HTTPD Service"
+              echo "########################################"
+              sudo systemctl start $SVC
+              sudo systemctl enable $SVC
+              echo
+
+              # Creating Temp Directory
+              echo "########################################"
+              echo "Starting Artifact Deployment"
+              echo "########################################"
+              mkdir -p $TEMPDIR
+              cd $TEMPDIR
+              echo
+
+              wget $URL > /dev/null
+              unzip $ART_NAME.zip > /dev/null
+              sudo cp -r $ART_NAME/* /var/www/html/
+              echo
+
+              # Bounce Service
+              echo "########################################"
+              echo "Restarting HTTPD service"
+              echo "########################################"
+              systemctl restart $SVC
+              echo
+
+              # Clean Up
+              echo "########################################"
+              echo "Removing Temporary Files"
+              echo "########################################"
+              rm -rf $TEMPDIR
+              echo
+
+              sudo systemctl status $SVC
+              ls /var/www/html/
+            fi 
+
   praneethSG:
     Type: AWS::EC2::SecurityGroup
     Properties:
@@ -68,3 +185,8 @@ Resources:
       VPCZoneIdentifier: 
         - subnet-031d506adca4ad569
         - subnet-09f5de7179cfc80d3
+
+Outputs:
+  praneethDNSOutput:
+    Description: DNSName of ELB
+    Value: !GetAtt praneethELB.DNSName
